### ISSUE TITLE
Alert failing to send

### ISSUE THREAD

**Issue by zodac-personal** [IamTheFij/minitor-go#3]
Hey, thanks for the project, looks like exactly what I'm looking for. :)

I'm trying to set up a simple check on my website, and have it send a message to a discord channel when the site is down/back up. I've copy/pasted the exact curl command listed in my own terminal and the messages send, so it doesn't seem to be an issue with the command. The failure output isn't very clear on a cause though.

Here is my config.yml:

```
---
check_interval: 5s

monitors:
  - name: Website
    command: [ "curl", "-s", "-o", "/dev/null", "--max-time", "5", "https://my.website.com" ]
    alert_down: [ discord_down ]
    alert_up: [ discord_up ]
    check_interval: 10s # Must be at minimum the global `check_interval`
    alert_after: 3
    alert_every: -1 # Defaults to -1 for exponential backoff. 0 to disable repeating

alerts:
  discord_up:
    command: >
      curl -s -X POST \
      -H "Accept: application/json" \
      -H "Content-Type: application/json" \
      --data "{\"content\": \"ONLINE\"}" \
      "https://discord.com/api/webhooks/url"
  discord_down:
    command: >
      curl -s -X POST \
      -H "Accept: application/json" \
      -H "Content-Type: application/json" \
      --data "{\"content\": \"OFFLINE\"}" \
      "https://discord.com/api/webhooks/url"
```

Here's the output logs, showing it can successfully check the website status, but then fails when sending the alert:

```
2022/12/29 03:03:00 INFO    Website success=true, alert=false
2022/12/29 03:03:11 INFO    Website success=true, alert=false
2022/12/29 03:03:26 WARNING Command result: exit status 28
2022/12/29 03:03:26 ERROR   exit status 28
2022/12/29 03:03:26 INFO    Website success=false, alert=false
2022/12/29 03:03:41 WARNING Command result: exit status 28
2022/12/29 03:03:41 ERROR   exit status 28
2022/12/29 03:03:41 INFO    Website success=false, alert=false
2022/12/29 03:03:56 WARNING Command result: exit status 28
2022/12/29 03:03:56 ERROR   exit status 28
2022/12/29 03:03:56 INFO    Website success=false, alert=true
2022/12/29 03:03:56 INFO    Sending alert discord_down for Website
2022/12/29 03:03:56 ERROR   Alert 'discord_down' failed. result=Alert 'discord_down' failed to send. Returned exit status 3: alert failed: output=
2022/12/29 03:03:56 ERROR   Error checking monitors
2022/12/29 03:03:56 ERROR   Alert 'discord_down' failed to send. Returned exit status 3: alert failed
panic: Alert 'discord_down' failed to send. Returned exit status 3: alert failed

goroutine 1 [running]:
log.(*Logger).Panic(0x12e36149b8, {0xc0001b3e78, 0xc0e35ebbc0300370, 0x0})
        /usr/local/go/src/log/log.go:224 +0x69
git.iamthefij.com/iamthefij/slog.OnErrPanicf({0x874180, 0xc000078080}, {0x7f9dd3, 0x7f56b0}, {0x0, 0x80c30e, 0x53})
        /go/pkg/mod/git.iamthefij.com/iamthefij/slog@v1.3.0/slog.go:111 +0x97
main.main()
        /drone/src/main.go:125 +0x385
```

**Comment by zodac-personal** [comment]
Never mind, silly mistake on my end. I shouldn't have had the trailing \ at the end of each line of my command. Removed them, and everything works as expected. :)
